appointment/urls.py
#
# Newfies-Dialer License
# http://www.newfies-dialer.org
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (C) 2011-2014 Star2Billing S.L.
#
# The Initial Developer of the Original Code is
# Arezqui Belaid <info@star2billing.com>
#
from django.conf.urls import patterns

urlpatterns = patterns('appointment.views',

    (r'^module/calendar_user/$', 'calendar_user_list'),
    (r'^module/calendar_user/add/$', 'calendar_user_add'),
    (r'^module/calendar_user/del/(.+)/$', 'calendar_user_del'),
    (r'^module/calendar_user/password/(.+)/$', 'calendar_user_change_password'),
    (r'^module/calendar_user/(.+)/$', 'calendar_user_change'),

    # Calendars urls
    (r'^module/calendar/$', 'calendar_list'),
    (r'^module/calendar/add/$', 'calendar_add'),
    (r'^module/calendar/del/(.+)/$', 'calendar_del'),
    (r'^module/calendar/(.+)/$', 'calendar_change'),

    # Calendar settings urls
    (r'^module/calendar_setting/$', 'calendar_setting_list'),
    (r'^module/calendar_setting/add/$', 'calendar_setting_add'),
    (r'^module/calendar_setting/del/(.+)/$', 'calendar_setting_del'),
    (r'^module/calendar_setting/(.+)/$', 'calendar_setting_change'),

    # Events urls
    (r'^module/event/$', 'event_list'),
    (r'^module/event/add/$', 'event_add'),
    (r'^module/event/del/(.+)/$', 'event_del'),
    (r'^module/event/(.+)/$', 'event_change'),

    # Alarms urls
    (r'^module/alarm/$', 'alarm_list'),
    (r'^module/alarm/add/$', 'alarm_add'),
    (r'^module/alarm/del/(.+)/$', 'alarm_del'),
    (r'^module/alarm/(.+)/$', 'alarm_change'),
)

dnc/urls.py
#
# Newfies-Dialer License
# http://www.newfies-dialer.org
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (C) 2011-2014 Star2Billing S.L.
#
# The Initial Developer of the Original Code is
# Arezqui Belaid <info@star2billing.com>
#

from django.conf.urls import patterns


urlpatterns = patterns('dnc.views',
    # DNC urls
    (r'^module/dnc_list/$', 'dnc_list'),
    (r'^module/dnc_list/add/$', 'dnc_add'),
    (r'^module/dnc_list/contact_count/$', 'get_dnc_contact_count'),
    (r'^module/dnc_list/del/(.+)/$', 'dnc_del'),
    (r'^module/dnc_list/(.+)/$', 'dnc_change'),

    # DNC Contacts urls
    (r'^module/dnc_contact/$', 'dnc_contact_list'),
    (r'^module/dnc_contact/add/$', 'dnc_contact_add'),
    (r'^module/dnc_contact_import/$', 'dnc_contact_import'),
    (r'^module/dnc_contact/export/$', 'dnc_contact_export'),
    (r'^module/dnc_contact/export_view/$', 'dnc_contact_export_view'),
    (r'^module/dnc_contact/del/(.+)/$', 'dnc_contact_del'),
    (r'^module/dnc_contact/(.+)/$', 'dnc_contact_change'),
)

newfies_dialer/urls.py
#
# Newfies-Dialer License
# http://www.newfies-dialer.org
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (C) 2011-2014 Star2Billing S.L.
#
# The Initial Developer of the Original Code is
# Arezqui Belaid <info@star2billing.com>
#
from django.conf.urls import handler404, handler500, \
    include, patterns, url
from django.conf import settings
from apirest.urls import urlpatterns as urlpatterns_apirest
from agent.api_urls import urlpatterns as urlpatterns_agent_apirest
from appointment.urls import urlpatterns as urlpatterns_appointment
from frontend.urls import urlpatterns as urlpatterns_frontend
from dialer_contact.urls import urlpatterns as urlpatterns_dialer_contact
from dialer_campaign.urls import urlpatterns as urlpatterns_dialer_campaign
from dialer_cdr.urls import urlpatterns as urlpatterns_dialer_cdr
from dnc.urls import urlpatterns as urlpatterns_dnc
from user_profile.urls import urlpatterns as urlpatterns_user_profile
from survey.urls import urlpatterns as urlpatterns_survey
from dialer_audio.urls import urlpatterns as urlpatterns_dialer_audio
from frontend_notification.urls import urlpatterns as urlpatterns_frontend_notification
#from agent.urls import urlpatterns as urlpatterns_agent
#from callcenter.urls import urlpatterns as urlpatterns_callcenter
from sms_module.urls import urlpatterns as urlpatterns_sms_module
from dajaxice.core import dajaxice_autodiscover, dajaxice_config
from django.contrib import admin
import os


admin.autodiscover()
dajaxice_autodiscover()

js_info_dict = {
    'domain': 'djangojs',
    'packages': ('dialer_campaign',
                 'user_profile',
                 'survey',
                 'audiofield'),
}

urlpatterns = patterns('',
    (r'^logout/$', 'frontend.views.logout_view'),
    (r'^admin/', include(admin.site.urls)),
    (r'^i18n/', include('django.conf.urls.i18n')),
    (r'^jsi18n/$', 'django.views.i18n.javascript_catalog', js_info_dict),
    (r'^admin_tools/', include('admin_tools.urls')),
    (r'^static/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': settings.STATIC_ROOT}),
    #(r'^sentry/', include('sentry.web.urls')),
    #(r'^%s/' % settings.DAJAXICE_MEDIA_PREFIX, include('dajaxice.urls')),
    url(dajaxice_config.dajaxice_url, include('dajaxice.urls')),
)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += patterns('',
        url(r'^__debug__/', include(debug_toolbar.urls)),
    )


urlpatterns += urlpatterns_apirest
urlpatterns += urlpatterns_agent_apirest
urlpatterns += urlpatterns_frontend
urlpatterns += urlpatterns_dialer_contact
urlpatterns += urlpatterns_dialer_campaign
urlpatterns += urlpatterns_dialer_cdr
urlpatterns += urlpatterns_dnc
urlpatterns += urlpatterns_user_profile
urlpatterns += urlpatterns_survey
urlpatterns += urlpatterns_dialer_audio
urlpatterns += urlpatterns_frontend_notification
#urlpatterns += urlpatterns_agent
#urlpatterns += urlpatterns_callcenter
urlpatterns += urlpatterns_appointment
urlpatterns += urlpatterns_sms_module

urlpatterns += patterns('',
    (r'^%s/(?P<path>.*)$' % settings.MEDIA_URL.strip(os.sep),
        'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
)


handler404 = 'urls.custom_404_view'
handler500 = 'urls.custom_500_view'


def custom_404_view(request, template_name='404.html'):
    """404 error handler which includes ``request`` in the context.

    Templates: `404.html`
    Context: None
    """
    from django.template import Context, loader
    from django.http import HttpResponseServerError

    t = loader.get_template('404.html')  # Need to create a 404.html template.
    return HttpResponseServerError(t.render(Context({
        'request': request,
    })))


def custom_500_view(request, template_name='500.html'):
    """500 error handler which includes ``request`` in the context.

    Templates: `500.html`
    Context: None
    """
    from django.template import Context, loader
    from django.http import HttpResponseServerError

    t = loader.get_template('500.html')  # Need to create a 500.html template.
    return HttpResponseServerError(t.render(Context({
        'request': request,
    })))

appointment/models/events.py
# -*- coding: utf-8 -*-
from django.db import models
from django.core.urlresolvers import reverse
from django.template.defaultfilters import date
from django.utils.translation import ugettext, ugettext_lazy as _
from django.utils import timezone
from appointment.models.rules import Rule
from appointment.models.calendars import Calendar
from appointment.models.users import CalendarUser
from appointment.utils import OccurrenceReplacer
from appointment.constants import EVENT_STATUS
from dateutil import rrule
from dateutil.relativedelta import relativedelta
from datetime import datetime
from django.utils.timezone import utc
import jsonfield
import pytz


class Event(models.Model):
    """
    This model stores meta data for a event
    """
    title = models.CharField(verbose_name=_("label"), max_length=255)
    description = models.TextField(verbose_name=_("description"), null=True, blank=True)
    start = models.DateTimeField(default=(lambda: datetime.utcnow().replace(tzinfo=utc)),
                                 verbose_name=_("start"))
    end = models.DateTimeField(default=(lambda: datetime.utcnow().replace(tzinfo=utc) + relativedelta(hours=+1)),
                               verbose_name=_("end"),
                               help_text=_("Must be later than the start"))
    creator = models.ForeignKey(CalendarUser, null=False, blank=False,
                                verbose_name=_("calendar user"), related_name='creator')
    created_on = models.DateTimeField(verbose_name=_("created on"), default=timezone.now)
    end_recurring_period = models.DateTimeField(verbose_name=_("end recurring period"),
                                                null=True, blank=True,
                                                default=(lambda: datetime.utcnow().replace(tzinfo=utc) + relativedelta(months=+1)),
                                                help_text=_("Used if the event recurs"))
    rule = models.ForeignKey(Rule, null=True, blank=True,
                             verbose_name=_("rule"), help_text=_("Recuring rules"))
    calendar = models.ForeignKey(Calendar, null=False, blank=False)

    notify_count = models.IntegerField(verbose_name=_("notify count"),
                                       null=True, blank=True, default=0)
    status = models.IntegerField(choices=list(EVENT_STATUS),
                                 default=EVENT_STATUS.PENDING,
                                 verbose_name=_("status"), blank=True, null=True)
    data = jsonfield.JSONField(null=True, blank=True, verbose_name=_('additional data (JSON)'),
                               help_text=_("data in JSON format, e.g. {\"cost\": \"40 euro\"}"))
    # Keep a trace of the original event of all occurences
    parent_event = models.ForeignKey('self', null=True, blank=True, related_name="parent event")
    # Occurence count, this is an increment that will add 1 on the new event created
    # This helps to know that an event is the nth created
    occ_count = models.IntegerField(null=True, blank=True, default=0,
                                    verbose_name=_("occurrence count"))

    class Meta:
        permissions = (
            ("view_event", _('can see Event list')),
        )
        verbose_name = _('event')
        verbose_name_plural = _('events')
        app_label = "appointment"

    def __unicode__(self):
        date_format = u'%s' % ugettext("DATE_FORMAT")
        return '%(title)s: %(start)s' % {
            'title': self.title,
            'start': date(self.start, date_format),
        }

    def get_absolute_url(self):
        return reverse('event', args=[self.id])

    def get_occurrences(self, start, end):
        """
        >>> rule = Rule(frequency="MONTHLY", name="Monthly")
        >>> rule.save()
        >>> event = Event(rule=rule, start=datetime.datetime(2008,1,1,tzinfo=pytz.utc), end=datetime.datetime(2008,1,2))
        >>> event.rule
        <Rule: Monthly>
        >>> occurrences = event.get_occurrences(datetime.datetime(2008,1,24), datetime.datetime(2008,3,2))
        >>> ["%s to %s" %(o.start, o.end) for o in occurrences]
        ['2008-02-01 00:00:00+00:00 to 2008-02-02 00:00:00+00:00', '2008-03-01 00:00:00+00:00 to 2008-03-02 00:00:00+00:00']

        Ensure that if an event has no rule, that it appears only once.

        >>> event = Event(start=datetime.datetime(2008,1,1,8,0), end=datetime.datetime(2008,1,1,9,0))
        >>> occurrences = event.get_occurrences(datetime.datetime(2013,1,24), datetime.datetime(2014,3,2))
        >>> ["%s to %s" %(o.start, o.end) for o in occurrences]
        []
        """
        persisted_occurrences = self.occurrence_set.all()
        occ_replacer = OccurrenceReplacer(persisted_occurrences)
        occurrences = self._get_occurrence_list(start, end)
        final_occurrences = []
        for occ in occurrences:
            # replace occurrences with their persisted counterparts
            if occ_replacer.has_occurrence(occ):
                p_occ = occ_replacer.get_occurrence(occ)
                # ...but only if they are within this period
                if p_occ.start < end and p_occ.end >= start:
                    final_occurrences.append(p_occ)
            else:
                final_occurrences.append(occ)
        # then add persisted occurrences which originated outside of this period but now
        # fall within it
        final_occurrences += occ_replacer.get_additional_occurrences(start, end)
        return final_occurrences

    def get_next_occurrence(self):
        """
        TODO: implement this

        >>> rule = Rule(frequency="MONTHLY", name="Monthly")
        >>> rule.save()
        >>> event = Event(rule=rule, start=datetime.datetime(2008,1,1,tzinfo=pytz.utc), end=datetime.datetime(2008,1,2))
        >>> event.rule
        <Rule: Monthly>
        >>> event.get_next_occurrence()
        2008-02-02 00:00:00+00:00
        """
        start = datetime.utcnow().replace(tzinfo=utc)
        for occ in self.get_rrule_object():
            if occ.replace(tzinfo=None) > start:
                return occ  # return the next occurent

    def copy_event(self, next_occurrence):
        """create new event with next occurrence"""

        if self.parent_event:
            parent_event = self.parent_event
        else:
            parent_event = self

        #find the new event end
        event_end = next_occurrence + (self.end - self.start)

        new_event = Event.objects.create(
            start=next_occurrence,
            end=event_end,
            title=self.title,
            description=self.description,
            creator=self.creator,
            rule=self.rule,
            end_recurring_period=self.end_recurring_period,
            calendar=self.calendar,
            notify_count=self.notify_count,
            data=self.data,
            # implemented parent_event & occ_count
            parent_event=parent_event,
            occ_count=self.occ_count + 1,
        )

        return new_event

    def update_last_child_status(self, status):
        """we will search for the last created child of an event and update his status
        to the status value

        Note for the integrators: We can pause an event for 12hours but after that we will have to
        stop and create the new event.
        """
        obj_events = Event.objects.filter(parent_event=self).order_by('-created_on')
        if obj_events:
            obj_events[0].status = status
            obj_events[0].save()

    def get_list_child(self):
        """we will list childs of an event"""
        obj_events = Event.objects.filter(parent_event=self).order_by('created_on')
        return obj_events

    def get_rrule_object(self):
        if self.rule is not None:
            params = self.rule.get_params()
            frequency = 'rrule.%s' % self.rule.frequency
            return rrule.rrule(eval(frequency), dtstart=self.start, **params)
        else:
            return []

    def _create_occurrence(self, start, end=None):
        if end is None:
            end = start + (self.end - self.start)
        return Occurrence(event=self, start=start, end=end, original_start=start, original_end=end)

    def get_occurrence(self, date):
        if timezone.is_naive(date):
            date = timezone.make_aware(date, timezone.utc)
        rule = self.get_rrule_object()
        if rule:
            next_occurrence = rule.after(date, inc=True)
        else:
            next_occurrence = self.start
        if next_occurrence == date:
            try:
                return Occurrence.objects.get(event=self, original_start=date)
            except Occurrence.DoesNotExist:
                return self._create_occurrence(next_occurrence)

    def _get_occurrence_list(self, start, end):
        """
        returns a list of occurrences for this event from start to end.
        """
        difference = (self.end - self.start)
        if self.rule is not None:
            occurrences = []
            if self.end_recurring_period and self.end_recurring_period < end:
                end = self.end_recurring_period
            rule = self.get_rrule_object()
            o_starts = rule.between(start - difference, end - difference, inc=True)
            for o_start in o_starts:
                o_end = o_start + difference
                occurrences.append(self._create_occurrence(o_start, o_end))
            return occurrences
        else:
            # check if event is in the period
            if self.start < end and self.end > start:
                return [self._create_occurrence(self.start)]
            else:
                return []

    def _occurrences_after_generator(self, after=None, tzinfo=pytz.utc):
        """
        returns a generator that produces unpresisted occurrences after the
        datetime ``after``.
        """

        if after is None:
            after = timezone.now()
        rule = self.get_rrule_object()
        if rule is None:

templates/frontend/appointment/event/change.html
{% extends "frontend/master.html" %}
{% load i18n common_tags %}

{% block extra_files %}
    {{ form.media }}
{% endblock %}

{% block content_header %}
    <h1>
        {% if action == 'update' %}
            {% trans "update"|title %}
        {% else %}
            {% trans "add"|title %}
        {% endif %}
        {% trans "event"|title %}
        <small></small>
    </h1>
{% endblock %}

{% block content %}

<form class="well" role="form" method="POST" action="." enctype="multipart/form-data">{% csrf_token %}
    <fieldset>
        <legend>{% trans "event settings"|title %}</legend>
        <div class="row">
            {% get_fieldset title,calendar,start,end,creator,end_recurring_period,rule as event_fields from form %}
            {% for field in event_fields.visible_fields %}
                <div class="col-md-6">
                    <div class="form-group {% if field.errors %}has-error{% endif %}">
                    <div class="col-xs-8">
                        <label class="control-label" for="{{ field.auto_id }}">{{ field.label|title }}</label>
                        {{ field }}
                        {% if field.errors %}
                            <span class="help-block">
                                {{ field.errors|removetags:"ul li"|safe }}
                            </span>
                        {% endif %}
                        <span class="help-block">
                            {{ field.help_text|capfirst }}
                        </span>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
        <div class="row">
            {% get_fieldset description,data as event_fields from form %}
            {% for field in event_fields.visible_fields %}
                <div class="col-md-6">
                    <div class="form-group {% if field.errors %}has-error{% endif %}">
                    <div class="col-xs-8">
                        <label class="control-label" for="{{ field.auto_id }}">{{ field.label|capfirst }}</label>
                        {{ field }}
                        {% if field.errors %}
                            <span class="help-block">
                                {{ field.errors|removetags:"ul li"|safe }}
                            </span>
                        {% endif %}
                        <span class="help-block">
                            {{ field.help_text|capfirst }}
                        </span>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    <fieldset>
    {% include "frontend/common_submit_buttons.html" %}
</form>

{% endblock %}

templates/frontend/appointment/event/list.html
{% extends "frontend/master.html" %}
{% load i18n pagination_tags common_tags appointment_tags %}

{% block extra_files %}
    {% include "frontend/custom_jquery_select_all.html" %}
    {{ form.media }}
{% endblock %}

{% block content_header %}
    <h1>{% trans "events"|title %} <small>{% trans "list, add and edit calendar events"|capfirst %}</small></h1>
{% endblock %}

{% block content %}
<div id="form_collapse" class="collapse">
    <form class="well form-search" method="POST" action="." enctype="multipart/form-data">
        {% csrf_token %}
        <div class="row">
            {% get_fieldset start_date,calendar_id,calendar_user_id as search_event from form %}
            {% for field in search_event %}
            <div class="col-md-4 {% if field.errors %} error{% endif %}">
                <label class="control-label" for="id_{{ field.name }}">{{ field.label|title }}</label>
                {{ field }}
                {% if field.errors %}
                    <span class="help-block">{{ field.errors|removetags:"ul li"|safe }}</span>
                {% endif %}
                <span class="help-block">{{ field.help_text|capfirst }} </span>
            </div>
            {% endfor %}
        </div>
        <input class="btn btn-primary" type=submit name=submit value={% trans "search"|title %} />
    </form>
</div>

<button id="toggle_btn" type="button" class="btn btn-default btn-sm" data-toggle="collapse" data-target="#form_collapse">
    <i id="toggle_btn_i" class="glyphicon glyphicon-zoom-in"></i>
    <span id="toggle_btn_i_span">{% trans "open search"|title %}</span>
</button>

<script type="text/javascript">
    function add_button()
    {
        window.location = 'add/';
    }

    function delete_button()
    {
        $('#ListForm').submit();
    }
</script>
<p>&nbsp;</p>
<div class="row">
    <div class="col-md-12">
        <div class="btn-group">
            <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
            {% trans "action"|capfirst %} <span class="caret"></span>
            </button>
            <ul class="dropdown-menu" role="menu">
                {% if perms.appointment.delete_event %}
                    <li><a href="#" onclick="delete_button()">{% trans "delete selected"|title %}</a></li>
                {% endif %}
            </ul>
        </div>

        {% if perms.appointment.add_event %}
            <button type="button" class="btn btn-info" onclick="add_button()">
                <i class="fa fa-plus"></i> {% trans "add"|title %}
            </button>
        {% endif %}
    </div>
</div>

<br/>

<div class="row">
    <div class="col-md-12">
        <form method="POST" action="del/0/" enctype="multipart/form-data" id="ListForm">{% csrf_token %}
            <div class="table-responsive">
                <table class="table table-striped table-bordered table-condensed">
                    <thead>
                    <tr>
                        <th><input type="checkbox" onclick="toggleChecked(this.checked)"></th>
                        <th>{% sort_link EVENT_COLUMN_NAME.start|capfirst col_name_with_order.start %}</th>
                        <th>{% sort_link EVENT_COLUMN_NAME.end|capfirst col_name_with_order.end %}</th>
                        <th>{% sort_link EVENT_COLUMN_NAME.title|capfirst col_name_with_order.title %}</th>
                        <th>{% sort_link EVENT_COLUMN_NAME.calendar|capfirst col_name_with_order.calendar %}</th>
                        <th>{% sort_link EVENT_COLUMN_NAME.status|capfirst col_name_with_order.status %}</th>
                        <th>{% trans 'action'|capfirst %}</th>
                    </tr>
                    </thead>
                    {% if event_list %}
                        {% autopaginate event_list PAGE_SIZE %}
                        {% for row in event_list %}
                            <tr>
                                <td><input type="checkbox" name="select" class="checkbox" value="{{ row.id }}" /></td>
                                <td>{{ row.start }}</td>
                                <td>{{ row.end }}</td>
                                <td>{{ row.title }}</td>
                                <td>{{ row.calendar }}</td>
                                <td>{{ row.status|event_status }}</td>
                                <td>
                                    {% if perms.appointment.change_event %}
                                        <a href="{{ row.id }}/" title="{% trans 'update event'|title %}"><i class="fa fa-edit"></i></a>
                                    {% endif %}
                                    {% if perms.appointment.delete_event %}
                                        <a id="id_delete_confirm" href="del/{{ row.id }}/" title="{% trans 'delete event'|title %}"><i class="fa fa-trash-o"></i></a>
                                    {% endif %}
                                </td>
                            </tr>
                        {% endfor %}
                    {% else %}
                        <tr>
                            <td colspan="9" align="center">
                                {% trans "no records found"|title %}
                            </td>
                        </tr>
                    {% endif %}
                </table>
            </div>
            <div class="text-right">
                {% trans "total"|title %} : {{ total_event }}
            </div>
            {% if event_list %}
                {% paginate %}
            {% endif %}
        </form>
    </div>
</div>
{% endblock %}