appointment/urls.py
#
# Newfies-Dialer License
# http://www.newfies-dialer.org
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (C) 2011-2014 Star2Billing S.L.
#
# The Initial Developer of the Original Code is
# Arezqui Belaid <info@star2billing.com>
#
from django.conf.urls import patterns

urlpatterns = patterns('appointment.views',

    (r'^module/calendar_user/$', 'calendar_user_list'),
    (r'^module/calendar_user/add/$', 'calendar_user_add'),
    (r'^module/calendar_user/del/(.+)/$', 'calendar_user_del'),
    (r'^module/calendar_user/password/(.+)/$', 'calendar_user_change_password'),
    (r'^module/calendar_user/(.+)/$', 'calendar_user_change'),

    # Calendars urls
    (r'^module/calendar/$', 'calendar_list'),
    (r'^module/calendar/add/$', 'calendar_add'),
    (r'^module/calendar/del/(.+)/$', 'calendar_del'),
    (r'^module/calendar/(.+)/$', 'calendar_change'),

    # Calendar settings urls
    (r'^module/calendar_setting/$', 'calendar_setting_list'),
    (r'^module/calendar_setting/add/$', 'calendar_setting_add'),
    (r'^module/calendar_setting/del/(.+)/$', 'calendar_setting_del'),
    (r'^module/calendar_setting/(.+)/$', 'calendar_setting_change'),

    # Events urls
    (r'^module/event/$', 'event_list'),
    (r'^module/event/add/$', 'event_add'),
    (r'^module/event/del/(.+)/$', 'event_del'),
    (r'^module/event/(.+)/$', 'event_change'),

    # Alarms urls
    (r'^module/alarm/$', 'alarm_list'),
    (r'^module/alarm/add/$', 'alarm_add'),
    (r'^module/alarm/del/(.+)/$', 'alarm_del'),
    (r'^module/alarm/(.+)/$', 'alarm_change'),
)

dnc/urls.py
#
# Newfies-Dialer License
# http://www.newfies-dialer.org
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (C) 2011-2014 Star2Billing S.L.
#
# The Initial Developer of the Original Code is
# Arezqui Belaid <info@star2billing.com>
#

from django.conf.urls import patterns


urlpatterns = patterns('dnc.views',
    # DNC urls
    (r'^module/dnc_list/$', 'dnc_list'),
    (r'^module/dnc_list/add/$', 'dnc_add'),
    (r'^module/dnc_list/contact_count/$', 'get_dnc_contact_count'),
    (r'^module/dnc_list/del/(.+)/$', 'dnc_del'),
    (r'^module/dnc_list/(.+)/$', 'dnc_change'),

    # DNC Contacts urls
    (r'^module/dnc_contact/$', 'dnc_contact_list'),
    (r'^module/dnc_contact/add/$', 'dnc_contact_add'),
    (r'^module/dnc_contact_import/$', 'dnc_contact_import'),
    (r'^module/dnc_contact/export/$', 'dnc_contact_export'),
    (r'^module/dnc_contact/export_view/$', 'dnc_contact_export_view'),
    (r'^module/dnc_contact/del/(.+)/$', 'dnc_contact_del'),
    (r'^module/dnc_contact/(.+)/$', 'dnc_contact_change'),
)

newfies_dialer/urls.py
#
# Newfies-Dialer License
# http://www.newfies-dialer.org
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (C) 2011-2014 Star2Billing S.L.
#
# The Initial Developer of the Original Code is
# Arezqui Belaid <info@star2billing.com>
#
from django.conf.urls import handler404, handler500, \
    include, patterns, url
from django.conf import settings
from apirest.urls import urlpatterns as urlpatterns_apirest
from agent.api_urls import urlpatterns as urlpatterns_agent_apirest
from appointment.urls import urlpatterns as urlpatterns_appointment
from frontend.urls import urlpatterns as urlpatterns_frontend
from dialer_contact.urls import urlpatterns as urlpatterns_dialer_contact
from dialer_campaign.urls import urlpatterns as urlpatterns_dialer_campaign
from dialer_cdr.urls import urlpatterns as urlpatterns_dialer_cdr
from dnc.urls import urlpatterns as urlpatterns_dnc
from user_profile.urls import urlpatterns as urlpatterns_user_profile
from survey.urls import urlpatterns as urlpatterns_survey
from dialer_audio.urls import urlpatterns as urlpatterns_dialer_audio
from frontend_notification.urls import urlpatterns as urlpatterns_frontend_notification
#from agent.urls import urlpatterns as urlpatterns_agent
#from callcenter.urls import urlpatterns as urlpatterns_callcenter
from sms_module.urls import urlpatterns as urlpatterns_sms_module
from dajaxice.core import dajaxice_autodiscover, dajaxice_config
from django.contrib import admin
import os


admin.autodiscover()
dajaxice_autodiscover()

js_info_dict = {
    'domain': 'djangojs',
    'packages': ('dialer_campaign',
                 'user_profile',
                 'survey',
                 'audiofield'),
}

urlpatterns = patterns('',
    (r'^logout/$', 'frontend.views.logout_view'),
    (r'^admin/', include(admin.site.urls)),
    (r'^i18n/', include('django.conf.urls.i18n')),
    (r'^jsi18n/$', 'django.views.i18n.javascript_catalog', js_info_dict),
    (r'^admin_tools/', include('admin_tools.urls')),
    (r'^static/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': settings.STATIC_ROOT}),
    #(r'^sentry/', include('sentry.web.urls')),
    #(r'^%s/' % settings.DAJAXICE_MEDIA_PREFIX, include('dajaxice.urls')),
    url(dajaxice_config.dajaxice_url, include('dajaxice.urls')),
)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += patterns('',
        url(r'^__debug__/', include(debug_toolbar.urls)),
    )


urlpatterns += urlpatterns_apirest
urlpatterns += urlpatterns_agent_apirest
urlpatterns += urlpatterns_frontend
urlpatterns += urlpatterns_dialer_contact
urlpatterns += urlpatterns_dialer_campaign
urlpatterns += urlpatterns_dialer_cdr
urlpatterns += urlpatterns_dnc
urlpatterns += urlpatterns_user_profile
urlpatterns += urlpatterns_survey
urlpatterns += urlpatterns_dialer_audio
urlpatterns += urlpatterns_frontend_notification
#urlpatterns += urlpatterns_agent
#urlpatterns += urlpatterns_callcenter
urlpatterns += urlpatterns_appointment
urlpatterns += urlpatterns_sms_module

urlpatterns += patterns('',
    (r'^%s/(?P<path>.*)$' % settings.MEDIA_URL.strip(os.sep),
        'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
)


handler404 = 'urls.custom_404_view'
handler500 = 'urls.custom_500_view'


def custom_404_view(request, template_name='404.html'):
    """404 error handler which includes ``request`` in the context.

    Templates: `404.html`
    Context: None
    """
    from django.template import Context, loader
    from django.http import HttpResponseServerError

    t = loader.get_template('404.html')  # Need to create a 404.html template.
    return HttpResponseServerError(t.render(Context({
        'request': request,
    })))


def custom_500_view(request, template_name='500.html'):
    """500 error handler which includes ``request`` in the context.

    Templates: `500.html`
    Context: None
    """
    from django.template import Context, loader
    from django.http import HttpResponseServerError

    t = loader.get_template('500.html')  # Need to create a 500.html template.
    return HttpResponseServerError(t.render(Context({
        'request': request,
    })))

appointment/models/calendars.py
# -*- coding: utf-8 -*-
from django.db import models
from django.core.urlresolvers import reverse
from django.utils.translation import ugettext_lazy as _
from django.utils import timezone
from appointment.models.users import CalendarUser
import datetime
import pytz


class Calendar(models.Model):
    """
    This is for grouping events so that batch relations can be made to all
    events.  An example would be a project calendar.

    name: the name of the calendar
    events: all the events contained within the calendar.
    >>> calendar = Calendar(name = 'Test Calendar')
    >>> calendar.save()
    """
    name = models.CharField(verbose_name=_('name'), max_length=200)
    user = models.ForeignKey(CalendarUser, blank=True, null=True,
                             verbose_name=_("calendar user"),
                             help_text=_("select user"),
                             related_name="calendar user")
    max_concurrent = models.IntegerField(null=True, blank=True, default=0,
                                         help_text=_("Max concurrent is not implemented"))
    created_date = models.DateTimeField(auto_now_add=True,
                                        verbose_name=_('date'))

    class Meta:
        permissions = (
            ("view_calendar", _('Can see Calendar list')),
        )
        verbose_name = _('calendar')
        verbose_name_plural = _('calendars')
        app_label = "appointment"

    def __unicode__(self):
        return self.name

    @property
    def events(self):
        return self.event_set

    def get_recent(self, amount=5, in_datetime=datetime.datetime.now, tzinfo=pytz.utc):
        """
        This shortcut function allows you to get events that have started recently.

        amount is the amount of events you want in the queryset. The default is 5.

        in_datetime is the datetime you want to check against.  It defaults to datetime.datetime.now
        """
        return self.events.order_by('-start').filter(start__lt=timezone.now())[:amount]

    def get_absolute_url(self):
        return reverse('calendar_home', kwargs={'calendar_slug': self.slug})

    def add_event_url(self):
        return reverse('s_create_event_in_calendar', args=[self.slug])

appointment/models/rules.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from dateutil import rrule

freqs = (
    ("YEARLY", _("Yearly")),
    ("MONTHLY", _("Monthly")),
    ("WEEKLY", _("Weekly")),
    ("DAILY", _("Daily")),
    ("HOURLY", _("Hourly")),
    ("MINUTELY", _("Minutely")),
    ("SECONDLY", _("Secondly"))
)


class Rule(models.Model):
    """
    This defines a rule by which an event will recur.  This is defined by the
    rrule in the dateutil documentation.

    * name - the human friendly name of this kind of recursion.
    * description - a short description describing this type of recursion.
    * frequency - the base recurrence period
    * param - extra params required to define this type of recursion. The params
      should follow this format:

        param = [rruleparam:value;]*
        rruleparam = see list below
        value = int[,int]*

      The options are: (documentation for these can be found at
      http://labix.org/python-dateutil#head-470fa22b2db72000d7abe698a5783a46b0731b57)
        ** count
        ** bysetpos
        ** bymonth
        ** bymonthday
        ** byyearday
        ** byweekno
        ** byweekday
        ** byhour
        ** byminute
        ** bysecond
        ** byeaster
    """
    name = models.CharField(verbose_name=_("name"), max_length=32)
    description = models.TextField(verbose_name=_("description"))
    frequency = models.CharField(verbose_name=_("frequency"), choices=freqs,
                                 max_length=10)
    params = models.TextField(verbose_name=_("params"), null=True, blank=True,
                              help_text=_("example : count:1;bysecond:3;"))

    class Meta:
        verbose_name = _('rule')
        verbose_name_plural = _('rules')
        app_label = "appointment"

    def get_params(self):
        """
        >>> rule = Rule(params = "count:1;bysecond:1;byminute:1,2,4,5")
        >>> rule.get_params()
        {'count': 1, 'byminute': [1, 2, 4, 5], 'bysecond': 1}

        >>> rule = Rule(params = "count:1;bysecond:3;byweekday:TU,WE,TH")
        >>> rule.get_params()
        {'bysecond': 1, 'byweekday': (TU, WE, TH), 'count': 1}
        """
        if self.params is None:
            return {}

        # remove "" from self.params
        params = self.params.replace('"', '')

        params = params.split(';')
        param_dict = []
        for param in params:
            param = param.split(':')
            if len(param) == 2:

                temp_list = []
                tuple_flag = False
                for p in param[1].split(','):
                    if p.isdigit():
                        temp_list.append(int(p))
                    else:
                        tuple_flag = True
                        temp_list.append(eval('rrule.%s' % str(p)))

                if tuple_flag:
                    temp_list = tuple(temp_list)

                param = (str(param[0]), temp_list)
                if len(param[1]) == 1:
                    param = (param[0], param[1][0])
                param_dict.append(param)
        return dict(param_dict)

    def __unicode__(self):
        """Human readable string for Rule"""
        return 'Rule %s params %s' % (self.name, self.params)

templates/frontend/appointment/calendar/change.html
{% extends "frontend/master.html" %}
{% load i18n %}

{% block content_header %}
    <h1>
        {% if action == 'update' %}
            {% trans "update"|title %}
        {% else %}
            {% trans "add"|title %}
        {% endif %}
        {% trans "calendar"|title %}
        <small></small>
    </h1>
{% endblock %}

{% block content %}

<form class="well" role="form" method="POST" action="." enctype="multipart/form-data">{% csrf_token %}
    {% for field in form %}
    <div class="row">
        <div class="form-group {% if field.errors %}has-error{% endif %}">
            <div class="col-xs-4">
                <label class="control-label" for="{{ field.auto_id }}">{{ field.label|title }}</label>
                {{ field }}
                {% if field.errors %}
                    <span class="help-block">{{ field.errors|removetags:"ul li"|safe }}</span>
                {% endif %}
                    <span class="help-block">{{ field.help_text|capfirst }} </span>
            </div>
        </div>
    </div>
    {% endfor %}
    {% include "frontend/common_submit_buttons.html" %}
</form>

{% endblock %}

templates/frontend/appointment/calendar/list.html
{% extends "frontend/master.html" %}
{% load i18n pagination_tags common_tags %}

{% block extra_files %}
    {% include "frontend/custom_jquery_select_all.html" %}
{% endblock %}

{% block content_header %}
    <h1>{% trans "calendars"|title %} <small>{% trans "list, add and edit calendar"|capfirst %}</small></h1>
{% endblock %}

{% block content %}

<script type="text/javascript">
    function add_button()
    {
        window.location = 'add/';
    }

    function delete_button()
    {
        $('#ListForm').submit();
    }
</script>

<div class="row">
    <div class="col-md-12">
        <div class="btn-group">
            <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
            {% trans "action"|capfirst %} <span class="caret"></span>
            </button>
            <ul class="dropdown-menu" role="menu">
                {% if perms.appointment.delete_calendar %}
                    <li><a href="#" onclick="delete_button()">{% trans "delete selected"|title %}</a></li>
                {% endif %}
            </ul>
        </div>
        {% if perms.appointment.add_calendar %}
            <button type="button" class="btn btn-info" onclick="add_button()">
                <i class="fa fa-plus"></i> {% trans "add"|title %}
            </button>
        {% endif %}
    </div>
</div>

<br/>

<div class="row">
    <div class="col-md-12">
        <form method="POST" role="form" action="del/0/" enctype="multipart/form-data" id="ListForm">{% csrf_token %}
            <div class="table-responsive">
                <table class="table table-striped table-bordered table-condensed">
                    <thead>
                    <tr>
                        <th><input type="checkbox" onclick="toggleChecked(this.checked)"></th>
                        <th>{% sort_link CALENDAR_COLUMN_NAME.name|title col_name_with_order.name %}</th>
                        <th>{% sort_link CALENDAR_COLUMN_NAME.user|title col_name_with_order.user %}</th>
                        <th>{% sort_link CALENDAR_COLUMN_NAME.max_concurrent|title col_name_with_order.max_concurrent %}</th>
                        <th>{% sort_link CALENDAR_COLUMN_NAME.created_date|title col_name_with_order.created_date %}</th>
                        <th>{% trans 'action'|title %}</th>
                    </tr>
                    </thead>
                    {% if calendar_list %}
                        {% autopaginate calendar_list PAGE_SIZE %}
                        {% for row in calendar_list %}
                            <tr>
                                <td><input type="checkbox" name="select" class="checkbox" value="{{ row.id }}" /></td>
                                <td>{{ row.name }}</td>
                                <td>{{ row.user }}</td>
                                <td>{{ row.max_concurrent }}</td>
                                <td>{{ row.created_date }}</td>
                                <td>
                                    {% if perms.appointment.change_calendar %}
                                        <a href="{{ row.id }}/" title="{% trans 'update calendar'|title %}"><i class="fa fa-edit"></i></a>
                                    {% endif %}
                                    {% if perms.appointment.delete_calendar %}
                                        <a id="id_delete_confirm" href="del/{{ row.id }}/" title="{% trans 'delete calendar'|title %}"><i class="fa fa-trash-o"></i></a>
                                    {% endif %}
                                </td>
                            </tr>
                        {% endfor %}
                    {% else %}
                        <tr>
                            <td colspan="6" align="center">
                                {% trans "no records found"|title %}
                            </td>
                        </tr>
                    {% endif %}
                </table>
            </div>
            <div class="text-right">
                {% trans "total"|title %} : {{ total_calendar }}
            </div>
            {% if calendar_list %}
                {% paginate %}
            {% endif %}
        </form>
    </div>
</div>
{% endblock %}